name: Build and push narrbase image

on:
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true

jobs:
  docker_build_image:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out GitHub Repo
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
      uses: actions/checkout@v2
    -
      name: Set up environment
      run: |
        if [ ${{ github.base_ref }} == 'main' ]; then
            branch=''
        else
            branch=`"-""${{ github.base_ref }}" | awk '{print tolower($0)}'`
        fi
        image_version=`cat VERSION`
        echo "IMAGE_VERSION=${image_version}" >> $GITHUB_ENV
        echo "APP_IMAGE_TAG=ghcr.io/kbase/narrbase${branch}:pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "BRANCH=${branch}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
        echo "PR=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "VCS_REF=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c -7)" >> $GITHUB_ENV
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    -
      name: Build narrative image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.APP_IMAGE_TAG }}
        build-args: |
          BRANCH=${{ github.head_ref }}
          BUILD_DATE=${{ env.BUILD_DATE }}
          IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          VCS_REF=${{ env.VCS_REF }}
        labels: |
          us.kbase.vcs-pull-req=pr-${{ env.PR }}
