---
name: Build and push narrative base image

on:
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true

jobs:
  docker_build_image:
    if: github.event.pull_request.draft == false
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: 'pr-${{ github.event.pull_request.number }}'
    secrets: inherit
