---
name: Build and push narrbase image

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    - ready_for_review

jobs:
  docker_build_image:
    if: github.event.pull_request.draft == false
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: 'pr-${{ github.event.pull_request.number }}'
    secrets: inherit
